name: Render slide.pdf
on:
  push:
    branches:
      - writing
    paths:
      - '*.typ'

permissions:
  contents: write

jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Restore or Save Cache - Font Noto
        id: cache-font-noto
        uses: actions/cache@v4
        with:
          path: /usr/share/fonts/opentype/noto
          key: font-noto-cache-key

      - name: Install fonts-noto
        run: sudo apt update && sudo apt install fonts-noto-cjk
        if: ${{ steps.cache-font-noto.outputs.cache-hit != 'true' }}

      - name: checkout
        uses: actions/checkout@v4
      
      - uses: typst-community/setup-typst@v4
      - name: Render slide
        run: typst compile slide.typ slide.pdf

      - name: commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add slide.pdf
          git commit -m "build slide.pdf"
          git push -u origin writing