name: review-feedback
on: issue_comment

jobs:
  feedback:
    name: test
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: feedback
      uses: actions/github-script@v7
      with:
        script: |
          const comment = context.payload.comment.body;
          const issueNumber = context.payload.issue.number;
          const repo = context.repo;

          if (!comment.includes('AI feedback')) {
            await github.rest.issues.createComment({
              ...repo,
              issue_number: issueNumber,
              body: `this is AI feedback\n Thank you for your feedback on PR #${issueNumber}!`
            });
          }
